---
abstract: 'A toolkit integrating intelligent PostgreSQL dbs into Perl objects'
author:
  - 'Chris Travers <chris.travers@gmail.com>'
build_requires:
  ExtUtils::MakeMaker: 0
configure_requires:
  ExtUtils::MakeMaker: 0
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 6.6302, CPAN::Meta::Converter version 2.120921'
license: bsd
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: PGObject
no_index:
  directory:
    - t
    - inc
requires:
  DBD::Pg: 2
  Test::Exception: 0
  Test::More: 0
version: 1.4
